version: '3.7'

services:
  telegram_bot:
    build: ./liza_bot
    image: liza_bot
    environment:

    ports:
      - "8080:8080"
    volumes:
      - ./liza_bot:/app
      - C:\Users\Evgenii\Desktop\liza_bot:/app/voice_response.mp3 
